language: ruby
rvm:
 - 2.4
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 906e626c483f789c8e7ee3ef77acacc20788edbe8f0dc35cf759f3eecd9f6a09
before_script:
  - psql -c 'create database magmonitor_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load
install:
  - bundle install
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  - nvm install lts/boron
  - node -v
  - npm i -g yarn
  - yarn
cache:
  bundler: true
  directories:
    - $HOME/.yarn-cache
  yarn: true
after_success:
  - bundle exec codeclimate-test-reporter
